---
apiVersion: apps/v1
kind: Deployment
metadata:
  ## deploy 生成的 pod 的名称也是 es-head-xxx
  name: es-head
  labels:
    app: es-head
spec:
  replicas: 1
  selector:
    matchLabels:
      ## 这里的 label 是与下面的 template -> metadata -> label 匹配的,
      ## 表示一种管理关系
      app: es-head
  template:
    metadata:
      labels:
        app: es-head
    spec:
      containers:
        - name: es-head
          image: mobz/elasticsearch-head:5
          imagePullPolicy: IfNotPresent
          env: 
            ## 这里的 es 指的是 service 名称
            - name: ELASTICSEARCH_HOSTS
              value: http://es-cluster:9200
