version: '3'

services:
  esc-master-0:
    image: elasticsearch:5.5.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ## 5.5.0 版本不支持在环境变量中直接使用 node.name 这样的键
      ES_NODE_NAME: esc-master-0
      ES_NODE_MASTER: "true"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/esc-master-0/data:/usr/share/elasticsearch/data
      ## - ./data/x-pack:/usr/share/elasticsearch/plugins/x-pack
  esc-master-1:
    image: elasticsearch:5.5.0
    environment:
      ## 5.5.0 版本不支持在环境变量中直接使用 node.name 这样的键
      ES_NODE_NAME: esc-master-1
      ES_NODE_MASTER: "true"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/esc-master-1/data:/usr/share/elasticsearch/data
      ## - ./data/x-pack:/usr/share/elasticsearch/plugins/x-pack
  esc-master-2:
    image: elasticsearch:5.5.0
    environment:
      ## 5.5.0 版本不支持在环境变量中直接使用 node.name 这样的键
      ES_NODE_NAME: esc-master-2
      ES_NODE_MASTER: "true"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/esc-master-2/data:/usr/share/elasticsearch/data
      ## - ./data/x-pack:/usr/share/elasticsearch/plugins/x-pack
  esc-data-0:
    image: elasticsearch:5.5.0
    environment:
      ## 5.5.0 版本不支持在环境变量中直接使用 node.name 这样的键
      ES_NODE_NAME: esc-data-0
      ES_NODE_DATA: "true"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/esc-data-0/data:/usr/share/elasticsearch/data
      ## - ./data/x-pack:/usr/share/elasticsearch/plugins/x-pack
  logstash:
    image: logstash:5.5.0
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/config/logstash.conf:ro
      - ./data/logs/nginx:/var/log/nginx
      ## logstash 5.5.0 貌似没有单独的 pipeline 目录
      ## - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    command: ["logstash", "-f", "/usr/share/logstash/config/logstash.conf"]
  kibana:
    image: kibana:5.5.0
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      ## - ./data/kibana/x-pack:/usr/share/elasticsearch/plugins/x-pack
  nginx:
    image: nginx:1.12.0
    ports:
      - 9001:8080
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./data/logs/nginx:/var/log/nginx
