version: '3'

services:
  esc-master-0:
    image: elasticsearch:5.5.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: esc-master-0
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  esc-master-1:
    image: elasticsearch:5.5.0
    environment:
      node.name: esc-master-1
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  esc-master-2:
    image: elasticsearch:5.5.0
    environment:
      node.name: esc-master-2
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  esc-data-0:
    image: elasticsearch:5.5.0
    environment:
      node.name: esc-data-0
      node.master: "false"
      node.data: "true"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  logstash:
    image: logstash:5.5.0
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/config/logstash.conf:ro
      - ./data/logs/nginx:/var/log/nginx
      ## logstash 5.5.0 貌似没有单独的 pipeline 目录
      ## - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    command: ["logstash", "-f", "/usr/share/logstash/config/logstash.conf"]
  kibana:
    image: kibana:5.5.0
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
  nginx:
    image: nginx:1.12.0
    ports:
      - 9001:8080
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./data/logs/nginx:/var/log/nginx
