cluster.name: esc
node.name: ${ES_NODE_NAME}
## 默认为 false
node.master: ${ES_NODE_MASTER:false}
node.data: ${ES_NODE_DATA:false}

network.host: 0.0.0.0
http.port: 9200
## path.data: /home/elasticsearch
bootstrap.memory_lock: false
bootstrap.system_call_filter: false
discovery.zen.ping.unicast.hosts: 
  - esc-master-0
  - esc-master-1
  - esc-master-2
